name: parser-cd

env:
  REDIS_PORT: ${{ secrets.REDIS_PORT }}
  REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
  REDIS_HOST: ${{ secrets.REDIS_HOST }}
  AMOCRM_TOKEN: ${{ secrets.AMOCRM_TOKEN }}
  AMOCRM_URL: ${{ secrets.AMOCRM_URL }}

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    name: Build and Push Docker Image
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Parser Image
        uses: docker/build-push-action@v4
        with:
          context: ./parser
          file: ./parser/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.PARSER_REPOSITORY_NAME }}:latest
          build-args: |
            REDIS_PORT=${{ env.REDIS_PORT }}
            REDIS_PASSWORD=${{ env.REDIS_PASSWORD }}
            REDIS_HOST=${{ env.REDIS_HOST }}
            AMOCRM_TOKEN=${{ env.AMOCRM_TOKEN }}
            AMOCRM_URL=${{ env.AMOCRM_URL }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote host to known_hosts
        run: ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Copy docker-compose file
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
            ./parser/docker-compose.yaml \
            ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.PATH_TO_PROJECT }}/docker-compose.parser.yml

      - name: Create .env file and set environment variables
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
          cd ${{ secrets.PATH_TO_PROJECT }}
          cat << 'ENV_EOF' > .env
          REDIS_PORT=${{ env.REDIS_PORT }}
          REDIS_PASSWORD=${{ env.REDIS_PASSWORD }}
          REDIS_HOST=${{ env.REDIS_HOST }}
          AMOCRM_TOKEN=${{ env.AMOCRM_TOKEN }}
          AMOCRM_URL=${{ env.AMOCRM_URL }}          
          DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ secrets.PARSER_REPOSITORY_NAME }}:latest
          ENV_EOF
          EOF

      - name: Deploy to production
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            cd ${{ secrets.PATH_TO_PROJECT }}
            chmod 600 .env

            if [ ! "$(docker ps -q -f name=redis)" ]; then
              docker compose -f docker-compose.parser.yml pull
              docker compose -f docker-compose.parser.yml up -d
            else
              docker compose -f docker-compose.parser.yml pull parser
              docker compose -f docker-compose.parser.yml up -d --no-deps parser
            fi

            docker system prune -f -a
          EOF
