name: server-cd

env:
  APPNAME: sales_prediction_agent
  API_PORT: ${{ secrets.SERVER_PORT }}
  NODE_ENV: prod
  LOCALE: false
  PRODUCTION_URL: ${{ secrets.PRODUCTION_URL }}
  CLIENT_BASE_URL: ${{ secrets.CLIENT_BASE_URL }}
  DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
  DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
  DATABASE_USER: ${{ secrets.DATABASE_USER }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  REDIS_PORT: ${{ secrets.REDIS_PORT }}
  REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
  REDIS_HOST: ${{ secrets.REDIS_HOST }}

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    name: Build and Push Docker Image
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Server Image
        uses: docker/build-push-action@v4
        with:
          context: ./server/Dockerfile
          file: ./server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.SERVER_REPOSITORY_NAME }}:latest
          build-args: |
            APPNAME=${{ env.APPNAME }}
            API_PORT=${{ env.API_PORT }}
            LOCALE=${{ env.LOCALE }}
            NODE_ENV=${{ env.NODE_ENV }}
            PRODUCTION_URL=${{ env.PRODUCTION_URL }}
            SECRET=${{ env.SECRET }}
            CLIENT_BASE_URL=${{ env.CLIENT_BASE_URL }}
            DATABASE_HOST=${{ env.DATABASE_HOST }}
            DATABASE_PORT=${{ env.DATABASE_PORT }}
            DATABASE_USER=${{ env.DATABASE_USER }}
            DATABASE_PASSWORD=${{ env.DATABASE_PASSWORD }}
            DATABASE_NAME=${{ env.DATABASE_NAME }}
            DATABASE_URL=${{ env.DATABASE_URL }}
            REDIS_PORT=${{ env.REDIS_PORT }}
            REDIS_PASSWORD=${{ env.REDIS_PASSWORD }}
            REDIS_HOST=${{ env.REDIS_HOST }}

  deploy:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    name: Deploy using Docker
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} > ~/.ssh/known_hosts

      - name: Copy docker-compose file
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
          ./server/docker-compose.yaml \
          ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.PATH_TO_PROJECT }}/docker-compose.yml

      - name: Create .env file and set enviroment variables
        run: |
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
          cd ${{ secrets.PATH_TO_PROJECT }}
          cat << 'ENV_EOF' > .env
          APPNAME=${{ env.APPNAME }}
          API_PORT=${{ env.API_PORT }}
          LOCALE=${{ env.LOCALE }}
          NODE_ENV=${{ env.NODE_ENV }}
          PRODUCTION_URL=${{ env.PRODUCTION_URL }}
          SECRET=${{ env.SECRET }}
          CLIENT_BASE_URL=${{ env.CLIENT_BASE_URL }}
          DATABASE_HOST=${{ env.DATABASE_HOST }}
          DATABASE_PORT=${{ env.DATABASE_PORT }}
          DATABASE_USER=${{ env.DATABASE_USER }}
          DATABASE_PASSWORD=${{ env.DATABASE_PASSWORD }}
          DATABASE_URL=${{ env.DATABASE_URL }}
          DATABASE_NAME=${{ env.DATABASE_NAME }}
          REDIS_PORT=${{ env.REDIS_PORT }}
          REDIS_PASSWORD=${{ env.REDIS_PASSWORD }}
          REDIS_HOST=${{ env.REDIS_HOST }}
          DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ secrets.SERVER_REPOSITORY_NAME }}:latest
          ENV_EOF

      - name: Deploy to production
        run: |
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            cd ${{ secrets.PATH_TO_PROJECT }}
            chmod 600 .env

            if [ -z "$(docker ps -q -f name=db)" ] && [ -z "$(docker ps -q -f name=redis)" ]; then
              docker compose pull
              docker compose up -d
            else
              docker compose pull server-app
              docker compose up -d --no-deps server-app
            fi

            docker system prune -f -a
          EOF